name: CI/CD

on:
  push:
    branches: ['master']

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up pnpm
        uses: pnpm/action-setup@v4.1.0
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: pnpm install
      - name: Code style check
        run: pnpm lint
      - name: Build the package
        run: pnpm build
      - name: Package verification
        run: pnpm publint
      - name: Publish to pkg.pr.new
        run: pnpm dlx pkg-pr-new publish --compact --pnpm
