name: Static code analysis

on:
  push:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up pnpm
        uses: pnpm/action-setup@v4.1.0
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install dependencies
        run: pnpm install
      - name: Code style check
        run: pnpm exec prettier --check .
      - run: pnpm build
      - name: Package verification
        run: pnpm publint
